Fix compilation errors on systems without BSD/GNU extensions
timegm is a BSD and GNU extension, it's not available on systems
like IBM AIX or some Solaris releases.  I provide an xtimegm()
here that uses only POSIX calls instead of BSD/GNU extensions.

While here, also fix a compiler warning about const correctness.

Errors were:
```
os.c: In function ‘uniqueName’:
os.c:181:17: warning: initialization discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
  181 |     char *ext = strrchr(fname, '.'); // ext in original name if present
      |                 ^~~~~~~
os.c:183:13: warning: assignment discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
  183 |         ext = strchr(fname, '\0'); // no ext so point to end of name
      |             ^
os.c: In function 'getFileTime':
os.c:50:12: warning: implicit declaration of function 'timegm'; did you mean 'time64'? [-Wimplicit-function-declaration]
   50 |     return timegm(localtime(&buf.st_mtime));
      |            ^~~~~~
      |            time64
support.c: In function 'cpmToOsTime':
support.c:98:29: warning: implicit declaration of function 'timegm'; did you mean 'time64'? [-Wimplicit-function-declaration]
   98 |         timeZero          = timegm(&timebuf);
      |                             ^~~~~~
      |                             time64
uncrunch.c: In function 'getCrunchTime':
uncrunch.c:136:12: warning: implicit declaration of function 'timegm'; did you mean 'time64'? [-Wimplicit-function-declaration]
  136 |     return timegm(&timebuf);
      |            ^~~~~~
      |            time64
```

Signed-off-by: Jeffrey H. Johnson <johnsonjh.dev@gmail.com>